name=ZE40B-TVOC
version=0.1.0
author=Juarendra Ramadhani <jrjuarendra@gmail.com>
maintainer=Juarendra Ramadhani <jrjuarendra@gmail.com>
sentence=Enterprise IoT Arduino library for the Winsen ZE40B-TVOC Gas Sensor.
paragraph=Enterprise IoT Arduino library for the Winsen ZE40B-TVOC Gas Sensor. Includes major enterprise features and bug fixes.
category=Sensors
url=https://github.com/juarendra/ZE40B-TVOC-Arduino
architectures=*
includes=ZE40BTVOC.h
