name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: submit
      - uses: arduino/setup-arduino-cli@v2
      - run: arduino-cli core update-index
      - run: arduino-cli core install esp32:esp32
      - run: arduino-cli compile --fqbn esp32:esp32:esp32 --libraries . examples/BasicRead
